<?xml version="1.0" encoding="utf-8"?><Database Name="mws_ctl" Class="mwsdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=mws_ctl;Persist Security Info=True;User ID=sa;Encrypt=False" SettingsObjectName="MWS.Properties.Settings" SettingsPropertyName="mws_ctlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MstBranch" Member="MstBranches">
    <Type Name="MstBranch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Branch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MstBranch_TrnProduction" Member="TrnProductions" ThisKey="Id" OtherKey="BranchId" Type="TrnProduction" />
      <Association Name="MstBranch_TrnPullOut" Member="TrnPullOuts" ThisKey="Id" OtherKey="BranchId" Type="TrnPullOut" />
      <Association Name="MstBranch_TrnReceiving" Member="TrnReceivings" ThisKey="Id" OtherKey="BranchId" Type="TrnReceiving" />
    </Type>
  </Table>
  <Table Name="dbo.TrnReceivingItem" Member="TrnReceivingItems">
    <Type Name="TrnReceivingItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceivingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ItemDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SizeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="TrnReceivingItem_TrnProductionItem" Member="TrnProductionItems" ThisKey="Id" OtherKey="ReceivingItemId" Type="TrnProductionItem" />
      <Association Name="MstItem_TrnReceivingItem" Member="MstItem" ThisKey="ItemId" OtherKey="Id" Type="MstItem" IsForeignKey="true" />
      <Association Name="MstSize_TrnReceivingItem" Member="MstSize" ThisKey="SizeId" OtherKey="Id" Type="MstSize" IsForeignKey="true" />
      <Association Name="TrnReceiving_TrnReceivingItem" Member="TrnReceiving" ThisKey="ReceivingId" OtherKey="Id" Type="TrnReceiving" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstItem" Member="MstItems">
    <Type Name="MstItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemDescription" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="MstItem_TrnReceivingItem" Member="TrnReceivingItems" ThisKey="Id" OtherKey="ItemId" Type="TrnReceivingItem" />
    </Type>
  </Table>
  <Table Name="dbo.MstSize" Member="MstSizes">
    <Type Name="MstSize">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MinWeight" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MaxWeight" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="MstSize_TrnReceivingItem" Member="TrnReceivingItems" ThisKey="Id" OtherKey="SizeId" Type="TrnReceivingItem" />
    </Type>
  </Table>
  <Table Name="dbo.MstSupplier" Member="MstSuppliers">
    <Type Name="MstSupplier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Supplier" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="MstSupplier_TrnReceiving" Member="TrnReceivings" ThisKey="Id" OtherKey="SupplierId" Type="TrnReceiving" />
    </Type>
  </Table>
  <Table Name="dbo.MstUser" Member="MstUsers">
    <Type Name="MstUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MstUser_TrnProduction" Member="TrnProductions" ThisKey="Id" OtherKey="PrepareById" Type="TrnProduction" />
      <Association Name="MstUser_TrnPullOut" Member="TrnPullOuts" ThisKey="Id" OtherKey="PrepareById" Type="TrnPullOut" />
      <Association Name="MstUser_TrnReceiving" Member="TrnReceivings" ThisKey="Id" OtherKey="PrepareById" Type="TrnReceiving" />
    </Type>
  </Table>
  <Table Name="dbo.TrnProduction" Member="TrnProductions">
    <Type Name="TrnProduction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductionNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrepareById" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrnProduction_TrnProductionItem" Member="TrnProductionItems" ThisKey="Id" OtherKey="ProductionId" Type="TrnProductionItem" />
      <Association Name="MstBranch_TrnProduction" Member="MstBranch" ThisKey="BranchId" OtherKey="Id" Type="MstBranch" IsForeignKey="true" />
      <Association Name="MstUser_TrnProduction" Member="MstUser" ThisKey="PrepareById" OtherKey="Id" Type="MstUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrnProductionItem" Member="TrnProductionItems">
    <Type Name="TrnProductionItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceivingItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductionBarcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ActualWeight" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="TrnProductionItem_TrnPullOutItem" Member="TrnPullOutItems" ThisKey="Id" OtherKey="ProductionItemId" Type="TrnPullOutItem" />
      <Association Name="TrnProduction_TrnProductionItem" Member="TrnProduction" ThisKey="ProductionId" OtherKey="Id" Type="TrnProduction" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TrnReceivingItem_TrnProductionItem" Member="TrnReceivingItem" ThisKey="ReceivingItemId" OtherKey="Id" Type="TrnReceivingItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrnPullOut" Member="TrnPullOuts">
    <Type Name="TrnPullOut">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PullOutNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PullOutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrepareById" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrnPullOut_TrnPullOutItem" Member="TrnPullOutItems" ThisKey="Id" OtherKey="PullOutId" Type="TrnPullOutItem" />
      <Association Name="MstBranch_TrnPullOut" Member="MstBranch" ThisKey="BranchId" OtherKey="Id" Type="MstBranch" IsForeignKey="true" />
      <Association Name="MstUser_TrnPullOut" Member="MstUser" ThisKey="PrepareById" OtherKey="Id" Type="MstUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrnPullOutItem" Member="TrnPullOutItems">
    <Type Name="TrnPullOutItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PullOutId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductionItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrnProductionItem_TrnPullOutItem" Member="TrnProductionItem" ThisKey="ProductionItemId" OtherKey="Id" Type="TrnProductionItem" IsForeignKey="true" />
      <Association Name="TrnPullOut_TrnPullOutItem" Member="TrnPullOut" ThisKey="PullOutId" OtherKey="Id" Type="TrnPullOut" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrnReceiving" Member="TrnReceivings">
    <Type Name="TrnReceiving">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceivingNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReceivingDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SupplierId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsLocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrepareById" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TrnReceiving_TrnReceivingItem" Member="TrnReceivingItems" ThisKey="Id" OtherKey="ReceivingId" Type="TrnReceivingItem" />
      <Association Name="MstBranch_TrnReceiving" Member="MstBranch" ThisKey="BranchId" OtherKey="Id" Type="MstBranch" IsForeignKey="true" />
      <Association Name="MstSupplier_TrnReceiving" Member="MstSupplier" ThisKey="SupplierId" OtherKey="Id" Type="MstSupplier" IsForeignKey="true" />
      <Association Name="MstUser_TrnReceiving" Member="MstUser" ThisKey="PrepareById" OtherKey="Id" Type="MstUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>