#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mws_ctl")]
	public partial class mwsdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMstBranch(MstBranch instance);
    partial void UpdateMstBranch(MstBranch instance);
    partial void DeleteMstBranch(MstBranch instance);
    partial void InsertTrnReceivingItem(TrnReceivingItem instance);
    partial void UpdateTrnReceivingItem(TrnReceivingItem instance);
    partial void DeleteTrnReceivingItem(TrnReceivingItem instance);
    partial void InsertMstItem(MstItem instance);
    partial void UpdateMstItem(MstItem instance);
    partial void DeleteMstItem(MstItem instance);
    partial void InsertMstSize(MstSize instance);
    partial void UpdateMstSize(MstSize instance);
    partial void DeleteMstSize(MstSize instance);
    partial void InsertMstSupplier(MstSupplier instance);
    partial void UpdateMstSupplier(MstSupplier instance);
    partial void DeleteMstSupplier(MstSupplier instance);
    partial void InsertMstUser(MstUser instance);
    partial void UpdateMstUser(MstUser instance);
    partial void DeleteMstUser(MstUser instance);
    partial void InsertTrnProduction(TrnProduction instance);
    partial void UpdateTrnProduction(TrnProduction instance);
    partial void DeleteTrnProduction(TrnProduction instance);
    partial void InsertTrnProductionItem(TrnProductionItem instance);
    partial void UpdateTrnProductionItem(TrnProductionItem instance);
    partial void DeleteTrnProductionItem(TrnProductionItem instance);
    partial void InsertTrnPullOut(TrnPullOut instance);
    partial void UpdateTrnPullOut(TrnPullOut instance);
    partial void DeleteTrnPullOut(TrnPullOut instance);
    partial void InsertTrnPullOutItem(TrnPullOutItem instance);
    partial void UpdateTrnPullOutItem(TrnPullOutItem instance);
    partial void DeleteTrnPullOutItem(TrnPullOutItem instance);
    partial void InsertTrnReceiving(TrnReceiving instance);
    partial void UpdateTrnReceiving(TrnReceiving instance);
    partial void DeleteTrnReceiving(TrnReceiving instance);
    #endregion
		
		public mwsdbDataContext() : 
				base(global::MWS.Properties.Settings.Default.mws_ctlConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public mwsdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mwsdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mwsdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mwsdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MstBranch> MstBranches
		{
			get
			{
				return this.GetTable<MstBranch>();
			}
		}
		
		public System.Data.Linq.Table<TrnReceivingItem> TrnReceivingItems
		{
			get
			{
				return this.GetTable<TrnReceivingItem>();
			}
		}
		
		public System.Data.Linq.Table<MstItem> MstItems
		{
			get
			{
				return this.GetTable<MstItem>();
			}
		}
		
		public System.Data.Linq.Table<MstSize> MstSizes
		{
			get
			{
				return this.GetTable<MstSize>();
			}
		}
		
		public System.Data.Linq.Table<MstSupplier> MstSuppliers
		{
			get
			{
				return this.GetTable<MstSupplier>();
			}
		}
		
		public System.Data.Linq.Table<MstUser> MstUsers
		{
			get
			{
				return this.GetTable<MstUser>();
			}
		}
		
		public System.Data.Linq.Table<TrnProduction> TrnProductions
		{
			get
			{
				return this.GetTable<TrnProduction>();
			}
		}
		
		public System.Data.Linq.Table<TrnProductionItem> TrnProductionItems
		{
			get
			{
				return this.GetTable<TrnProductionItem>();
			}
		}
		
		public System.Data.Linq.Table<TrnPullOut> TrnPullOuts
		{
			get
			{
				return this.GetTable<TrnPullOut>();
			}
		}
		
		public System.Data.Linq.Table<TrnPullOutItem> TrnPullOutItems
		{
			get
			{
				return this.GetTable<TrnPullOutItem>();
			}
		}
		
		public System.Data.Linq.Table<TrnReceiving> TrnReceivings
		{
			get
			{
				return this.GetTable<TrnReceiving>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstBranch")]
	public partial class MstBranch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Branch;
		
		private EntitySet<TrnProduction> _TrnProductions;
		
		private EntitySet<TrnPullOut> _TrnPullOuts;
		
		private EntitySet<TrnReceiving> _TrnReceivings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    #endregion
		
		public MstBranch()
		{
			this._TrnProductions = new EntitySet<TrnProduction>(new Action<TrnProduction>(this.attach_TrnProductions), new Action<TrnProduction>(this.detach_TrnProductions));
			this._TrnPullOuts = new EntitySet<TrnPullOut>(new Action<TrnPullOut>(this.attach_TrnPullOuts), new Action<TrnPullOut>(this.detach_TrnPullOuts));
			this._TrnReceivings = new EntitySet<TrnReceiving>(new Action<TrnReceiving>(this.attach_TrnReceivings), new Action<TrnReceiving>(this.detach_TrnReceivings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this.OnBranchChanging(value);
					this.SendPropertyChanging();
					this._Branch = value;
					this.SendPropertyChanged("Branch");
					this.OnBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstBranch_TrnProduction", Storage="_TrnProductions", ThisKey="Id", OtherKey="BranchId")]
		public EntitySet<TrnProduction> TrnProductions
		{
			get
			{
				return this._TrnProductions;
			}
			set
			{
				this._TrnProductions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstBranch_TrnPullOut", Storage="_TrnPullOuts", ThisKey="Id", OtherKey="BranchId")]
		public EntitySet<TrnPullOut> TrnPullOuts
		{
			get
			{
				return this._TrnPullOuts;
			}
			set
			{
				this._TrnPullOuts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstBranch_TrnReceiving", Storage="_TrnReceivings", ThisKey="Id", OtherKey="BranchId")]
		public EntitySet<TrnReceiving> TrnReceivings
		{
			get
			{
				return this._TrnReceivings;
			}
			set
			{
				this._TrnReceivings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnProductions(TrnProduction entity)
		{
			this.SendPropertyChanging();
			entity.MstBranch = this;
		}
		
		private void detach_TrnProductions(TrnProduction entity)
		{
			this.SendPropertyChanging();
			entity.MstBranch = null;
		}
		
		private void attach_TrnPullOuts(TrnPullOut entity)
		{
			this.SendPropertyChanging();
			entity.MstBranch = this;
		}
		
		private void detach_TrnPullOuts(TrnPullOut entity)
		{
			this.SendPropertyChanging();
			entity.MstBranch = null;
		}
		
		private void attach_TrnReceivings(TrnReceiving entity)
		{
			this.SendPropertyChanging();
			entity.MstBranch = this;
		}
		
		private void detach_TrnReceivings(TrnReceiving entity)
		{
			this.SendPropertyChanging();
			entity.MstBranch = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnReceivingItem")]
	public partial class TrnReceivingItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ReceivingId;
		
		private int _ItemId;
		
		private string _Barcode;
		
		private string _ItemDescription;
		
		private int _SizeId;
		
		private decimal _Weight;
		
		private EntitySet<TrnProductionItem> _TrnProductionItems;
		
		private EntityRef<MstItem> _MstItem;
		
		private EntityRef<MstSize> _MstSize;
		
		private EntityRef<TrnReceiving> _TrnReceiving;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnReceivingIdChanging(int value);
    partial void OnReceivingIdChanged();
    partial void OnItemIdChanging(int value);
    partial void OnItemIdChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnItemDescriptionChanging(string value);
    partial void OnItemDescriptionChanged();
    partial void OnSizeIdChanging(int value);
    partial void OnSizeIdChanged();
    partial void OnWeightChanging(decimal value);
    partial void OnWeightChanged();
    #endregion
		
		public TrnReceivingItem()
		{
			this._TrnProductionItems = new EntitySet<TrnProductionItem>(new Action<TrnProductionItem>(this.attach_TrnProductionItems), new Action<TrnProductionItem>(this.detach_TrnProductionItems));
			this._MstItem = default(EntityRef<MstItem>);
			this._MstSize = default(EntityRef<MstSize>);
			this._TrnReceiving = default(EntityRef<TrnReceiving>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivingId", DbType="Int NOT NULL")]
		public int ReceivingId
		{
			get
			{
				return this._ReceivingId;
			}
			set
			{
				if ((this._ReceivingId != value))
				{
					if (this._TrnReceiving.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReceivingIdChanging(value);
					this.SendPropertyChanging();
					this._ReceivingId = value;
					this.SendPropertyChanged("ReceivingId");
					this.OnReceivingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int NOT NULL")]
		public int ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					if (this._MstItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDescription", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemDescription
		{
			get
			{
				return this._ItemDescription;
			}
			set
			{
				if ((this._ItemDescription != value))
				{
					this.OnItemDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ItemDescription = value;
					this.SendPropertyChanged("ItemDescription");
					this.OnItemDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeId", DbType="Int NOT NULL")]
		public int SizeId
		{
			get
			{
				return this._SizeId;
			}
			set
			{
				if ((this._SizeId != value))
				{
					if (this._MstSize.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSizeIdChanging(value);
					this.SendPropertyChanging();
					this._SizeId = value;
					this.SendPropertyChanged("SizeId");
					this.OnSizeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(18,2) NOT NULL")]
		public decimal Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnReceivingItem_TrnProductionItem", Storage="_TrnProductionItems", ThisKey="Id", OtherKey="ReceivingItemId")]
		public EntitySet<TrnProductionItem> TrnProductionItems
		{
			get
			{
				return this._TrnProductionItems;
			}
			set
			{
				this._TrnProductionItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstItem_TrnReceivingItem", Storage="_MstItem", ThisKey="ItemId", OtherKey="Id", IsForeignKey=true)]
		public MstItem MstItem
		{
			get
			{
				return this._MstItem.Entity;
			}
			set
			{
				MstItem previousValue = this._MstItem.Entity;
				if (((previousValue != value) 
							|| (this._MstItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstItem.Entity = null;
						previousValue.TrnReceivingItems.Remove(this);
					}
					this._MstItem.Entity = value;
					if ((value != null))
					{
						value.TrnReceivingItems.Add(this);
						this._ItemId = value.Id;
					}
					else
					{
						this._ItemId = default(int);
					}
					this.SendPropertyChanged("MstItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSize_TrnReceivingItem", Storage="_MstSize", ThisKey="SizeId", OtherKey="Id", IsForeignKey=true)]
		public MstSize MstSize
		{
			get
			{
				return this._MstSize.Entity;
			}
			set
			{
				MstSize previousValue = this._MstSize.Entity;
				if (((previousValue != value) 
							|| (this._MstSize.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstSize.Entity = null;
						previousValue.TrnReceivingItems.Remove(this);
					}
					this._MstSize.Entity = value;
					if ((value != null))
					{
						value.TrnReceivingItems.Add(this);
						this._SizeId = value.Id;
					}
					else
					{
						this._SizeId = default(int);
					}
					this.SendPropertyChanged("MstSize");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnReceiving_TrnReceivingItem", Storage="_TrnReceiving", ThisKey="ReceivingId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TrnReceiving TrnReceiving
		{
			get
			{
				return this._TrnReceiving.Entity;
			}
			set
			{
				TrnReceiving previousValue = this._TrnReceiving.Entity;
				if (((previousValue != value) 
							|| (this._TrnReceiving.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrnReceiving.Entity = null;
						previousValue.TrnReceivingItems.Remove(this);
					}
					this._TrnReceiving.Entity = value;
					if ((value != null))
					{
						value.TrnReceivingItems.Add(this);
						this._ReceivingId = value.Id;
					}
					else
					{
						this._ReceivingId = default(int);
					}
					this.SendPropertyChanged("TrnReceiving");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnProductionItems(TrnProductionItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnReceivingItem = this;
		}
		
		private void detach_TrnProductionItems(TrnProductionItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnReceivingItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstItem")]
	public partial class MstItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ItemDescription;
		
		private EntitySet<TrnReceivingItem> _TrnReceivingItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemDescriptionChanging(string value);
    partial void OnItemDescriptionChanged();
    #endregion
		
		public MstItem()
		{
			this._TrnReceivingItems = new EntitySet<TrnReceivingItem>(new Action<TrnReceivingItem>(this.attach_TrnReceivingItems), new Action<TrnReceivingItem>(this.detach_TrnReceivingItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDescription", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ItemDescription
		{
			get
			{
				return this._ItemDescription;
			}
			set
			{
				if ((this._ItemDescription != value))
				{
					this.OnItemDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ItemDescription = value;
					this.SendPropertyChanged("ItemDescription");
					this.OnItemDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstItem_TrnReceivingItem", Storage="_TrnReceivingItems", ThisKey="Id", OtherKey="ItemId")]
		public EntitySet<TrnReceivingItem> TrnReceivingItems
		{
			get
			{
				return this._TrnReceivingItems;
			}
			set
			{
				this._TrnReceivingItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnReceivingItems(TrnReceivingItem entity)
		{
			this.SendPropertyChanging();
			entity.MstItem = this;
		}
		
		private void detach_TrnReceivingItems(TrnReceivingItem entity)
		{
			this.SendPropertyChanging();
			entity.MstItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstSize")]
	public partial class MstSize : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Size;
		
		private decimal _MinWeight;
		
		private decimal _MaxWeight;
		
		private EntitySet<TrnReceivingItem> _TrnReceivingItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnMinWeightChanging(decimal value);
    partial void OnMinWeightChanged();
    partial void OnMaxWeightChanging(decimal value);
    partial void OnMaxWeightChanged();
    #endregion
		
		public MstSize()
		{
			this._TrnReceivingItems = new EntitySet<TrnReceivingItem>(new Action<TrnReceivingItem>(this.attach_TrnReceivingItems), new Action<TrnReceivingItem>(this.detach_TrnReceivingItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinWeight", DbType="Decimal(18,2) NOT NULL")]
		public decimal MinWeight
		{
			get
			{
				return this._MinWeight;
			}
			set
			{
				if ((this._MinWeight != value))
				{
					this.OnMinWeightChanging(value);
					this.SendPropertyChanging();
					this._MinWeight = value;
					this.SendPropertyChanged("MinWeight");
					this.OnMinWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxWeight", DbType="Decimal(18,2) NOT NULL")]
		public decimal MaxWeight
		{
			get
			{
				return this._MaxWeight;
			}
			set
			{
				if ((this._MaxWeight != value))
				{
					this.OnMaxWeightChanging(value);
					this.SendPropertyChanging();
					this._MaxWeight = value;
					this.SendPropertyChanged("MaxWeight");
					this.OnMaxWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSize_TrnReceivingItem", Storage="_TrnReceivingItems", ThisKey="Id", OtherKey="SizeId")]
		public EntitySet<TrnReceivingItem> TrnReceivingItems
		{
			get
			{
				return this._TrnReceivingItems;
			}
			set
			{
				this._TrnReceivingItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnReceivingItems(TrnReceivingItem entity)
		{
			this.SendPropertyChanging();
			entity.MstSize = this;
		}
		
		private void detach_TrnReceivingItems(TrnReceivingItem entity)
		{
			this.SendPropertyChanging();
			entity.MstSize = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstSupplier")]
	public partial class MstSupplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Supplier;
		
		private EntitySet<TrnReceiving> _TrnReceivings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSupplierChanging(string value);
    partial void OnSupplierChanged();
    #endregion
		
		public MstSupplier()
		{
			this._TrnReceivings = new EntitySet<TrnReceiving>(new Action<TrnReceiving>(this.attach_TrnReceivings), new Action<TrnReceiving>(this.detach_TrnReceivings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Supplier
		{
			get
			{
				return this._Supplier;
			}
			set
			{
				if ((this._Supplier != value))
				{
					this.OnSupplierChanging(value);
					this.SendPropertyChanging();
					this._Supplier = value;
					this.SendPropertyChanged("Supplier");
					this.OnSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSupplier_TrnReceiving", Storage="_TrnReceivings", ThisKey="Id", OtherKey="SupplierId")]
		public EntitySet<TrnReceiving> TrnReceivings
		{
			get
			{
				return this._TrnReceivings;
			}
			set
			{
				this._TrnReceivings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnReceivings(TrnReceiving entity)
		{
			this.SendPropertyChanging();
			entity.MstSupplier = this;
		}
		
		private void detach_TrnReceivings(TrnReceiving entity)
		{
			this.SendPropertyChanging();
			entity.MstSupplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstUser")]
	public partial class MstUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Username;
		
		private string _Password;
		
		private string _FullName;
		
		private bool _IsLocked;
		
		private EntitySet<TrnProduction> _TrnProductions;
		
		private EntitySet<TrnPullOut> _TrnPullOuts;
		
		private EntitySet<TrnReceiving> _TrnReceivings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    #endregion
		
		public MstUser()
		{
			this._TrnProductions = new EntitySet<TrnProduction>(new Action<TrnProduction>(this.attach_TrnProductions), new Action<TrnProduction>(this.detach_TrnProductions));
			this._TrnPullOuts = new EntitySet<TrnPullOut>(new Action<TrnPullOut>(this.attach_TrnPullOuts), new Action<TrnPullOut>(this.detach_TrnPullOuts));
			this._TrnReceivings = new EntitySet<TrnReceiving>(new Action<TrnReceiving>(this.attach_TrnReceivings), new Action<TrnReceiving>(this.detach_TrnReceivings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstUser_TrnProduction", Storage="_TrnProductions", ThisKey="Id", OtherKey="PrepareById")]
		public EntitySet<TrnProduction> TrnProductions
		{
			get
			{
				return this._TrnProductions;
			}
			set
			{
				this._TrnProductions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstUser_TrnPullOut", Storage="_TrnPullOuts", ThisKey="Id", OtherKey="PrepareById")]
		public EntitySet<TrnPullOut> TrnPullOuts
		{
			get
			{
				return this._TrnPullOuts;
			}
			set
			{
				this._TrnPullOuts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstUser_TrnReceiving", Storage="_TrnReceivings", ThisKey="Id", OtherKey="PrepareById")]
		public EntitySet<TrnReceiving> TrnReceivings
		{
			get
			{
				return this._TrnReceivings;
			}
			set
			{
				this._TrnReceivings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnProductions(TrnProduction entity)
		{
			this.SendPropertyChanging();
			entity.MstUser = this;
		}
		
		private void detach_TrnProductions(TrnProduction entity)
		{
			this.SendPropertyChanging();
			entity.MstUser = null;
		}
		
		private void attach_TrnPullOuts(TrnPullOut entity)
		{
			this.SendPropertyChanging();
			entity.MstUser = this;
		}
		
		private void detach_TrnPullOuts(TrnPullOut entity)
		{
			this.SendPropertyChanging();
			entity.MstUser = null;
		}
		
		private void attach_TrnReceivings(TrnReceiving entity)
		{
			this.SendPropertyChanging();
			entity.MstUser = this;
		}
		
		private void detach_TrnReceivings(TrnReceiving entity)
		{
			this.SendPropertyChanging();
			entity.MstUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnProduction")]
	public partial class TrnProduction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _BranchId;
		
		private string _ProductionNo;
		
		private System.DateTime _ProductionDate;
		
		private string _Remarks;
		
		private bool _IsLocked;
		
		private int _PrepareById;
		
		private EntitySet<TrnProductionItem> _TrnProductionItems;
		
		private EntityRef<MstBranch> _MstBranch;
		
		private EntityRef<MstUser> _MstUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBranchIdChanging(int value);
    partial void OnBranchIdChanged();
    partial void OnProductionNoChanging(string value);
    partial void OnProductionNoChanged();
    partial void OnProductionDateChanging(System.DateTime value);
    partial void OnProductionDateChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    partial void OnPrepareByIdChanging(int value);
    partial void OnPrepareByIdChanged();
    #endregion
		
		public TrnProduction()
		{
			this._TrnProductionItems = new EntitySet<TrnProductionItem>(new Action<TrnProductionItem>(this.attach_TrnProductionItems), new Action<TrnProductionItem>(this.detach_TrnProductionItems));
			this._MstBranch = default(EntityRef<MstBranch>);
			this._MstUser = default(EntityRef<MstUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="Int NOT NULL")]
		public int BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					if (this._MstBranch.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBranchIdChanging(value);
					this.SendPropertyChanging();
					this._BranchId = value;
					this.SendPropertyChanged("BranchId");
					this.OnBranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductionNo
		{
			get
			{
				return this._ProductionNo;
			}
			set
			{
				if ((this._ProductionNo != value))
				{
					this.OnProductionNoChanging(value);
					this.SendPropertyChanging();
					this._ProductionNo = value;
					this.SendPropertyChanged("ProductionNo");
					this.OnProductionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionDate", DbType="DateTime NOT NULL")]
		public System.DateTime ProductionDate
		{
			get
			{
				return this._ProductionDate;
			}
			set
			{
				if ((this._ProductionDate != value))
				{
					this.OnProductionDateChanging(value);
					this.SendPropertyChanging();
					this._ProductionDate = value;
					this.SendPropertyChanged("ProductionDate");
					this.OnProductionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrepareById", DbType="Int NOT NULL")]
		public int PrepareById
		{
			get
			{
				return this._PrepareById;
			}
			set
			{
				if ((this._PrepareById != value))
				{
					if (this._MstUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPrepareByIdChanging(value);
					this.SendPropertyChanging();
					this._PrepareById = value;
					this.SendPropertyChanged("PrepareById");
					this.OnPrepareByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnProduction_TrnProductionItem", Storage="_TrnProductionItems", ThisKey="Id", OtherKey="ProductionId")]
		public EntitySet<TrnProductionItem> TrnProductionItems
		{
			get
			{
				return this._TrnProductionItems;
			}
			set
			{
				this._TrnProductionItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstBranch_TrnProduction", Storage="_MstBranch", ThisKey="BranchId", OtherKey="Id", IsForeignKey=true)]
		public MstBranch MstBranch
		{
			get
			{
				return this._MstBranch.Entity;
			}
			set
			{
				MstBranch previousValue = this._MstBranch.Entity;
				if (((previousValue != value) 
							|| (this._MstBranch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstBranch.Entity = null;
						previousValue.TrnProductions.Remove(this);
					}
					this._MstBranch.Entity = value;
					if ((value != null))
					{
						value.TrnProductions.Add(this);
						this._BranchId = value.Id;
					}
					else
					{
						this._BranchId = default(int);
					}
					this.SendPropertyChanged("MstBranch");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstUser_TrnProduction", Storage="_MstUser", ThisKey="PrepareById", OtherKey="Id", IsForeignKey=true)]
		public MstUser MstUser
		{
			get
			{
				return this._MstUser.Entity;
			}
			set
			{
				MstUser previousValue = this._MstUser.Entity;
				if (((previousValue != value) 
							|| (this._MstUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstUser.Entity = null;
						previousValue.TrnProductions.Remove(this);
					}
					this._MstUser.Entity = value;
					if ((value != null))
					{
						value.TrnProductions.Add(this);
						this._PrepareById = value.Id;
					}
					else
					{
						this._PrepareById = default(int);
					}
					this.SendPropertyChanged("MstUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnProductionItems(TrnProductionItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnProduction = this;
		}
		
		private void detach_TrnProductionItems(TrnProductionItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnProduction = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnProductionItem")]
	public partial class TrnProductionItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ProductionId;
		
		private int _ReceivingItemId;
		
		private string _ProductionBarcode;
		
		private decimal _ActualWeight;
		
		private EntitySet<TrnPullOutItem> _TrnPullOutItems;
		
		private EntityRef<TrnProduction> _TrnProduction;
		
		private EntityRef<TrnReceivingItem> _TrnReceivingItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProductionIdChanging(int value);
    partial void OnProductionIdChanged();
    partial void OnReceivingItemIdChanging(int value);
    partial void OnReceivingItemIdChanged();
    partial void OnProductionBarcodeChanging(string value);
    partial void OnProductionBarcodeChanged();
    partial void OnActualWeightChanging(decimal value);
    partial void OnActualWeightChanged();
    #endregion
		
		public TrnProductionItem()
		{
			this._TrnPullOutItems = new EntitySet<TrnPullOutItem>(new Action<TrnPullOutItem>(this.attach_TrnPullOutItems), new Action<TrnPullOutItem>(this.detach_TrnPullOutItems));
			this._TrnProduction = default(EntityRef<TrnProduction>);
			this._TrnReceivingItem = default(EntityRef<TrnReceivingItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionId", DbType="Int NOT NULL")]
		public int ProductionId
		{
			get
			{
				return this._ProductionId;
			}
			set
			{
				if ((this._ProductionId != value))
				{
					if (this._TrnProduction.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductionIdChanging(value);
					this.SendPropertyChanging();
					this._ProductionId = value;
					this.SendPropertyChanged("ProductionId");
					this.OnProductionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivingItemId", DbType="Int NOT NULL")]
		public int ReceivingItemId
		{
			get
			{
				return this._ReceivingItemId;
			}
			set
			{
				if ((this._ReceivingItemId != value))
				{
					if (this._TrnReceivingItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReceivingItemIdChanging(value);
					this.SendPropertyChanging();
					this._ReceivingItemId = value;
					this.SendPropertyChanged("ReceivingItemId");
					this.OnReceivingItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionBarcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductionBarcode
		{
			get
			{
				return this._ProductionBarcode;
			}
			set
			{
				if ((this._ProductionBarcode != value))
				{
					this.OnProductionBarcodeChanging(value);
					this.SendPropertyChanging();
					this._ProductionBarcode = value;
					this.SendPropertyChanged("ProductionBarcode");
					this.OnProductionBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualWeight", DbType="Decimal(18,2) NOT NULL")]
		public decimal ActualWeight
		{
			get
			{
				return this._ActualWeight;
			}
			set
			{
				if ((this._ActualWeight != value))
				{
					this.OnActualWeightChanging(value);
					this.SendPropertyChanging();
					this._ActualWeight = value;
					this.SendPropertyChanged("ActualWeight");
					this.OnActualWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnProductionItem_TrnPullOutItem", Storage="_TrnPullOutItems", ThisKey="Id", OtherKey="ProductionItemId")]
		public EntitySet<TrnPullOutItem> TrnPullOutItems
		{
			get
			{
				return this._TrnPullOutItems;
			}
			set
			{
				this._TrnPullOutItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnProduction_TrnProductionItem", Storage="_TrnProduction", ThisKey="ProductionId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TrnProduction TrnProduction
		{
			get
			{
				return this._TrnProduction.Entity;
			}
			set
			{
				TrnProduction previousValue = this._TrnProduction.Entity;
				if (((previousValue != value) 
							|| (this._TrnProduction.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrnProduction.Entity = null;
						previousValue.TrnProductionItems.Remove(this);
					}
					this._TrnProduction.Entity = value;
					if ((value != null))
					{
						value.TrnProductionItems.Add(this);
						this._ProductionId = value.Id;
					}
					else
					{
						this._ProductionId = default(int);
					}
					this.SendPropertyChanged("TrnProduction");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnReceivingItem_TrnProductionItem", Storage="_TrnReceivingItem", ThisKey="ReceivingItemId", OtherKey="Id", IsForeignKey=true)]
		public TrnReceivingItem TrnReceivingItem
		{
			get
			{
				return this._TrnReceivingItem.Entity;
			}
			set
			{
				TrnReceivingItem previousValue = this._TrnReceivingItem.Entity;
				if (((previousValue != value) 
							|| (this._TrnReceivingItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrnReceivingItem.Entity = null;
						previousValue.TrnProductionItems.Remove(this);
					}
					this._TrnReceivingItem.Entity = value;
					if ((value != null))
					{
						value.TrnProductionItems.Add(this);
						this._ReceivingItemId = value.Id;
					}
					else
					{
						this._ReceivingItemId = default(int);
					}
					this.SendPropertyChanged("TrnReceivingItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnPullOutItems(TrnPullOutItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnProductionItem = this;
		}
		
		private void detach_TrnPullOutItems(TrnPullOutItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnProductionItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnPullOut")]
	public partial class TrnPullOut : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _BranchId;
		
		private string _PullOutNo;
		
		private System.DateTime _PullOutDate;
		
		private string _Remarks;
		
		private bool _IsLocked;
		
		private int _PrepareById;
		
		private EntitySet<TrnPullOutItem> _TrnPullOutItems;
		
		private EntityRef<MstBranch> _MstBranch;
		
		private EntityRef<MstUser> _MstUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBranchIdChanging(int value);
    partial void OnBranchIdChanged();
    partial void OnPullOutNoChanging(string value);
    partial void OnPullOutNoChanged();
    partial void OnPullOutDateChanging(System.DateTime value);
    partial void OnPullOutDateChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    partial void OnPrepareByIdChanging(int value);
    partial void OnPrepareByIdChanged();
    #endregion
		
		public TrnPullOut()
		{
			this._TrnPullOutItems = new EntitySet<TrnPullOutItem>(new Action<TrnPullOutItem>(this.attach_TrnPullOutItems), new Action<TrnPullOutItem>(this.detach_TrnPullOutItems));
			this._MstBranch = default(EntityRef<MstBranch>);
			this._MstUser = default(EntityRef<MstUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="Int NOT NULL")]
		public int BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					if (this._MstBranch.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBranchIdChanging(value);
					this.SendPropertyChanging();
					this._BranchId = value;
					this.SendPropertyChanged("BranchId");
					this.OnBranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PullOutNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PullOutNo
		{
			get
			{
				return this._PullOutNo;
			}
			set
			{
				if ((this._PullOutNo != value))
				{
					this.OnPullOutNoChanging(value);
					this.SendPropertyChanging();
					this._PullOutNo = value;
					this.SendPropertyChanged("PullOutNo");
					this.OnPullOutNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PullOutDate", DbType="DateTime NOT NULL")]
		public System.DateTime PullOutDate
		{
			get
			{
				return this._PullOutDate;
			}
			set
			{
				if ((this._PullOutDate != value))
				{
					this.OnPullOutDateChanging(value);
					this.SendPropertyChanging();
					this._PullOutDate = value;
					this.SendPropertyChanged("PullOutDate");
					this.OnPullOutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrepareById", DbType="Int NOT NULL")]
		public int PrepareById
		{
			get
			{
				return this._PrepareById;
			}
			set
			{
				if ((this._PrepareById != value))
				{
					if (this._MstUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPrepareByIdChanging(value);
					this.SendPropertyChanging();
					this._PrepareById = value;
					this.SendPropertyChanged("PrepareById");
					this.OnPrepareByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnPullOut_TrnPullOutItem", Storage="_TrnPullOutItems", ThisKey="Id", OtherKey="PullOutId")]
		public EntitySet<TrnPullOutItem> TrnPullOutItems
		{
			get
			{
				return this._TrnPullOutItems;
			}
			set
			{
				this._TrnPullOutItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstBranch_TrnPullOut", Storage="_MstBranch", ThisKey="BranchId", OtherKey="Id", IsForeignKey=true)]
		public MstBranch MstBranch
		{
			get
			{
				return this._MstBranch.Entity;
			}
			set
			{
				MstBranch previousValue = this._MstBranch.Entity;
				if (((previousValue != value) 
							|| (this._MstBranch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstBranch.Entity = null;
						previousValue.TrnPullOuts.Remove(this);
					}
					this._MstBranch.Entity = value;
					if ((value != null))
					{
						value.TrnPullOuts.Add(this);
						this._BranchId = value.Id;
					}
					else
					{
						this._BranchId = default(int);
					}
					this.SendPropertyChanged("MstBranch");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstUser_TrnPullOut", Storage="_MstUser", ThisKey="PrepareById", OtherKey="Id", IsForeignKey=true)]
		public MstUser MstUser
		{
			get
			{
				return this._MstUser.Entity;
			}
			set
			{
				MstUser previousValue = this._MstUser.Entity;
				if (((previousValue != value) 
							|| (this._MstUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstUser.Entity = null;
						previousValue.TrnPullOuts.Remove(this);
					}
					this._MstUser.Entity = value;
					if ((value != null))
					{
						value.TrnPullOuts.Add(this);
						this._PrepareById = value.Id;
					}
					else
					{
						this._PrepareById = default(int);
					}
					this.SendPropertyChanged("MstUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnPullOutItems(TrnPullOutItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnPullOut = this;
		}
		
		private void detach_TrnPullOutItems(TrnPullOutItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnPullOut = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnPullOutItem")]
	public partial class TrnPullOutItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _PullOutId;
		
		private int _ProductionItemId;
		
		private EntityRef<TrnProductionItem> _TrnProductionItem;
		
		private EntityRef<TrnPullOut> _TrnPullOut;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPullOutIdChanging(int value);
    partial void OnPullOutIdChanged();
    partial void OnProductionItemIdChanging(int value);
    partial void OnProductionItemIdChanged();
    #endregion
		
		public TrnPullOutItem()
		{
			this._TrnProductionItem = default(EntityRef<TrnProductionItem>);
			this._TrnPullOut = default(EntityRef<TrnPullOut>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PullOutId", DbType="Int NOT NULL")]
		public int PullOutId
		{
			get
			{
				return this._PullOutId;
			}
			set
			{
				if ((this._PullOutId != value))
				{
					if (this._TrnPullOut.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPullOutIdChanging(value);
					this.SendPropertyChanging();
					this._PullOutId = value;
					this.SendPropertyChanged("PullOutId");
					this.OnPullOutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionItemId", DbType="Int NOT NULL")]
		public int ProductionItemId
		{
			get
			{
				return this._ProductionItemId;
			}
			set
			{
				if ((this._ProductionItemId != value))
				{
					if (this._TrnProductionItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductionItemIdChanging(value);
					this.SendPropertyChanging();
					this._ProductionItemId = value;
					this.SendPropertyChanged("ProductionItemId");
					this.OnProductionItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnProductionItem_TrnPullOutItem", Storage="_TrnProductionItem", ThisKey="ProductionItemId", OtherKey="Id", IsForeignKey=true)]
		public TrnProductionItem TrnProductionItem
		{
			get
			{
				return this._TrnProductionItem.Entity;
			}
			set
			{
				TrnProductionItem previousValue = this._TrnProductionItem.Entity;
				if (((previousValue != value) 
							|| (this._TrnProductionItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrnProductionItem.Entity = null;
						previousValue.TrnPullOutItems.Remove(this);
					}
					this._TrnProductionItem.Entity = value;
					if ((value != null))
					{
						value.TrnPullOutItems.Add(this);
						this._ProductionItemId = value.Id;
					}
					else
					{
						this._ProductionItemId = default(int);
					}
					this.SendPropertyChanged("TrnProductionItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnPullOut_TrnPullOutItem", Storage="_TrnPullOut", ThisKey="PullOutId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TrnPullOut TrnPullOut
		{
			get
			{
				return this._TrnPullOut.Entity;
			}
			set
			{
				TrnPullOut previousValue = this._TrnPullOut.Entity;
				if (((previousValue != value) 
							|| (this._TrnPullOut.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrnPullOut.Entity = null;
						previousValue.TrnPullOutItems.Remove(this);
					}
					this._TrnPullOut.Entity = value;
					if ((value != null))
					{
						value.TrnPullOutItems.Add(this);
						this._PullOutId = value.Id;
					}
					else
					{
						this._PullOutId = default(int);
					}
					this.SendPropertyChanged("TrnPullOut");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnReceiving")]
	public partial class TrnReceiving : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _BranchId;
		
		private string _ReceivingNo;
		
		private System.DateTime _ReceivingDate;
		
		private int _SupplierId;
		
		private string _Remarks;
		
		private bool _IsLocked;
		
		private int _PrepareById;
		
		private EntitySet<TrnReceivingItem> _TrnReceivingItems;
		
		private EntityRef<MstBranch> _MstBranch;
		
		private EntityRef<MstSupplier> _MstSupplier;
		
		private EntityRef<MstUser> _MstUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBranchIdChanging(int value);
    partial void OnBranchIdChanged();
    partial void OnReceivingNoChanging(string value);
    partial void OnReceivingNoChanged();
    partial void OnReceivingDateChanging(System.DateTime value);
    partial void OnReceivingDateChanged();
    partial void OnSupplierIdChanging(int value);
    partial void OnSupplierIdChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    partial void OnPrepareByIdChanging(int value);
    partial void OnPrepareByIdChanged();
    #endregion
		
		public TrnReceiving()
		{
			this._TrnReceivingItems = new EntitySet<TrnReceivingItem>(new Action<TrnReceivingItem>(this.attach_TrnReceivingItems), new Action<TrnReceivingItem>(this.detach_TrnReceivingItems));
			this._MstBranch = default(EntityRef<MstBranch>);
			this._MstSupplier = default(EntityRef<MstSupplier>);
			this._MstUser = default(EntityRef<MstUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="Int NOT NULL")]
		public int BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					if (this._MstBranch.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBranchIdChanging(value);
					this.SendPropertyChanging();
					this._BranchId = value;
					this.SendPropertyChanged("BranchId");
					this.OnBranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivingNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReceivingNo
		{
			get
			{
				return this._ReceivingNo;
			}
			set
			{
				if ((this._ReceivingNo != value))
				{
					this.OnReceivingNoChanging(value);
					this.SendPropertyChanging();
					this._ReceivingNo = value;
					this.SendPropertyChanged("ReceivingNo");
					this.OnReceivingNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivingDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReceivingDate
		{
			get
			{
				return this._ReceivingDate;
			}
			set
			{
				if ((this._ReceivingDate != value))
				{
					this.OnReceivingDateChanging(value);
					this.SendPropertyChanging();
					this._ReceivingDate = value;
					this.SendPropertyChanged("ReceivingDate");
					this.OnReceivingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierId", DbType="Int NOT NULL")]
		public int SupplierId
		{
			get
			{
				return this._SupplierId;
			}
			set
			{
				if ((this._SupplierId != value))
				{
					if (this._MstSupplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSupplierIdChanging(value);
					this.SendPropertyChanging();
					this._SupplierId = value;
					this.SendPropertyChanged("SupplierId");
					this.OnSupplierIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrepareById", DbType="Int NOT NULL")]
		public int PrepareById
		{
			get
			{
				return this._PrepareById;
			}
			set
			{
				if ((this._PrepareById != value))
				{
					if (this._MstUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPrepareByIdChanging(value);
					this.SendPropertyChanging();
					this._PrepareById = value;
					this.SendPropertyChanged("PrepareById");
					this.OnPrepareByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrnReceiving_TrnReceivingItem", Storage="_TrnReceivingItems", ThisKey="Id", OtherKey="ReceivingId")]
		public EntitySet<TrnReceivingItem> TrnReceivingItems
		{
			get
			{
				return this._TrnReceivingItems;
			}
			set
			{
				this._TrnReceivingItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstBranch_TrnReceiving", Storage="_MstBranch", ThisKey="BranchId", OtherKey="Id", IsForeignKey=true)]
		public MstBranch MstBranch
		{
			get
			{
				return this._MstBranch.Entity;
			}
			set
			{
				MstBranch previousValue = this._MstBranch.Entity;
				if (((previousValue != value) 
							|| (this._MstBranch.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstBranch.Entity = null;
						previousValue.TrnReceivings.Remove(this);
					}
					this._MstBranch.Entity = value;
					if ((value != null))
					{
						value.TrnReceivings.Add(this);
						this._BranchId = value.Id;
					}
					else
					{
						this._BranchId = default(int);
					}
					this.SendPropertyChanged("MstBranch");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSupplier_TrnReceiving", Storage="_MstSupplier", ThisKey="SupplierId", OtherKey="Id", IsForeignKey=true)]
		public MstSupplier MstSupplier
		{
			get
			{
				return this._MstSupplier.Entity;
			}
			set
			{
				MstSupplier previousValue = this._MstSupplier.Entity;
				if (((previousValue != value) 
							|| (this._MstSupplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstSupplier.Entity = null;
						previousValue.TrnReceivings.Remove(this);
					}
					this._MstSupplier.Entity = value;
					if ((value != null))
					{
						value.TrnReceivings.Add(this);
						this._SupplierId = value.Id;
					}
					else
					{
						this._SupplierId = default(int);
					}
					this.SendPropertyChanged("MstSupplier");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstUser_TrnReceiving", Storage="_MstUser", ThisKey="PrepareById", OtherKey="Id", IsForeignKey=true)]
		public MstUser MstUser
		{
			get
			{
				return this._MstUser.Entity;
			}
			set
			{
				MstUser previousValue = this._MstUser.Entity;
				if (((previousValue != value) 
							|| (this._MstUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MstUser.Entity = null;
						previousValue.TrnReceivings.Remove(this);
					}
					this._MstUser.Entity = value;
					if ((value != null))
					{
						value.TrnReceivings.Add(this);
						this._PrepareById = value.Id;
					}
					else
					{
						this._PrepareById = default(int);
					}
					this.SendPropertyChanged("MstUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TrnReceivingItems(TrnReceivingItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnReceiving = this;
		}
		
		private void detach_TrnReceivingItems(TrnReceivingItem entity)
		{
			this.SendPropertyChanging();
			entity.TrnReceiving = null;
		}
	}
}
#pragma warning restore 1591
